### ISSUE TITLE
Got this warning when running in simulation and no camera is connected to my PC.

### ISSUE THREAD

**Issue by mwulmer** [mwulmer/sai2_environment#8]
Exception in thread background:
Traceback (most recent call last):
  File "/home/maxwulmer/anaconda3/envs/rrl/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/maxwulmer/anaconda3/envs/rrl/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maxwulmer/sai2/apps/learning_test/sai2_environment/sai2_environment/robot_env.py", line 89, in get_frames
    self.pipeline.start()
RuntimeError: No device connected

**Comment by ElieAljalbout** [comment]
I fixed that in the last commit, can you please pull and try again?
